app:
  baseUrl: https://backstage-demo.westus3.cloudapp.azure.com

organization:
  name: Demo 

permission:
  enabled: true

backend:
  baseUrl: https://backstage-demo.westus3.cloudapp.azure.com
  listen:
    port: 7007
  cors:
    origin: [https://backstage-demo.westus3.cloudapp.azure.com]
  csp:
    upgrade-insecure-requests: false
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      ssl:
        rejectUnauthorized: false



auth:
  environment: production
  providers:
    microsoft:
      production:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail
              dangerouslyAllowSignInWithoutUserInCatalog: true



integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

catalog:
  providers:
    microsoftGraphOrg:
      default:
        target: https://graph.microsoft.com/v1.0
        authority: https://login.microsoftonline.com
        tenantId: ${AZURE_TENANT_ID}
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        user:
          filter: accountEnabled eq true
        group:
          filter: securityEnabled eq true
        schedule:
          frequency: { hours: 1 }
          timeout: { minutes: 50 }
          initialDelay: { seconds: 15 }

  locations:
    - type: url
      target: https://github.com/lderdzyan/azure-function-software-template/blob/main/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/lderdzyan/azure-function-software-template/blob/main/org.yaml
      rules:
        - allow: [Group, User]
  
techdocs:
  builder: 'external'
  publisher:
    type: 'azureBlobStorage'
    azureBlobStorage:
      containerName: 'techdocs'
      credentials:
        accountName: ${AZURE_STORAGE_ACCOUNT_NAME}